### ISSUE TITLE
Remote app not connecting to computer app

### ISSUE THREAD

**Issue by AndreiAndrone** [ArvidNy/quelea-flutter-remote#2]
The wrong page content was found. Please try again!

This is the error I’m getting on my mobile app when trying to connect to the computer app. The url works when opened in a browser, but the app keeps showing the same message. Every now and then, when I restart the remote app, it tells me to enter the password, but then the same error appears.

**Comment by ArvidNy** [comment]
I've just submitted new versions to Google Play and App Store that should resolve this issue. They should be available within a few days (especially depending on the Apple review process). Let me know when you've tried it if it works as expected.

**Comment by UserShofar** [comment]
Good day

Even after an update was done, it still persist with the same error.

Please advise?

**Comment by ArvidNy** [comment]
Can you provide me with more details about your setup:
- What device do you use?
- What's the operating system version of your device?
- Can you connect to the URL in your device's web browser?
